#!/bin/bash
DIR=$(dirname $(realpath $0)) 
CHANNEL_FILE=$DIR/radio.dat
PID_FILE=/tmp/radio_$USER.pid

CMD=$1
shift

if [ "x$CMD" == "x" ]
then
    CMD=list
fi

if [ -e $PID_FILE ]
then
    CURPID=$(head -n 1 $PID_FILE)
    CURSHA=$(tail -n 1 $PID_FILE)
fi

if [ "x$CMD" == "xlist" ]
then
    if [ "x$CURSHA" != "x" ]
    then
        echo "Playing:"
        echo $CURSHA
    fi
    echo "Channels:"
    cat $CHANNEL_FILE
    exit 0
fi

if [ "x$CURPID" != "x" ]
then
    kill $CURPID
    rm -f $PID_FILE
fi

if [ "x$CMD" == "xstop" ]
then
    exit 0
fi

PLAYLIST=$(sed -n "/^$CMD/ { s/$CMD //p; x }" $CHANNEL_FILE)
echo $PLAYLIST

if [ "x$PLAYLIST" == "x" ]
then
    echo "Channel not found. Select from:"
    cat $CHANNEL_FILE
    exit 1
fi

mplayer -really-quiet -playlist $PLAYLIST &
echo $! > $PID_FILE
echo "$CMD $PLAYLIST" >> $PID_FILE

