#!/bin/bash
DIR=$(dirname $(realpath $0)) 
CHANNEL_FILE=$DIR/radio.dat
PID_FILE=/tmp/radio.pid

if [ "x$1" == "xlist" ]
then
    cat $CHANNEL_FILE
    exit 0
fi

if [ -e $PID_FILE ]
then
    kill $(cat $PID_FILE)
    rm -f $PID_FILE
fi

if [ "x$1" == "xstop" ]
then
    exit 0
fi

PLAYLIST=$(sed -n "/^$1/ { s/$1 //p; x }" $CHANNEL_FILE)
echo $PLAYLIST
if [ "x$PLAYLIST" == "x" ]
then
    echo "Channel not found. Select from:"
    cat $CHANNEL_FILE
    exit 1
fi

mplayer -really-quiet -playlist $PLAYLIST &
echo $! > $PID_FILE

